---
- name: Common tasks FTW
  hosts: all
  sudo: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}
    - name: Install git client
      apt: name=git state=installed
  roles:
  - role: python

- hosts: base
  roles:
  - role: panda-service
  - role: big-service

#- name: Base bamboo service
#  hosts: base
#  sudo: yes
#  roles:
#    - { role: nodejs, tags: nodejs }
#    - { role: bamboo, tags: bamboo }
